name: GBA and NES Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NES tools
        run: |
          apt-get update
          apt-get install -y cc65

      - name: Build GBA
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=$DEVKITPRO/devkitARM
          export PATH=$PATH:$DEVKITARM/bin:$DEVKITPRO/tools/bin
          arm-none-eabi-gcc -mthumb -mthumb-interwork -I$DEVKITPRO/libtonc/include -L$DEVKITPRO/libtonc/lib -specs=gba.specs balls.c -o balls.elf -O3 -ltonc
          arm-none-eabi-objcopy -O binary balls.elf GoogleBalls.gba
          gbafix GoogleBalls.gba

      - name: Build NES
        run: |
          cl65 -t nes -O -o GoogleBalls.nes nes/balls.c neslib.lib

      - name: Set Tag Name
        id: vars
        run: echo "tag=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          files: |
            GoogleBalls.gba
            GoogleBalls.nes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
